spring:
  application:
    name: medical-repository-test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${APP_POSTGRESQL_SCHEMA:public}
        order_inserts: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 20
        generate_statistics: false
        show_sql: true
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5442/mis_medical_service?currentSchema=public}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}